package com.myblue.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.myblue.dao.BlueFey;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BLUE_FEY".
*/
public class BlueFeyDao extends AbstractDao<BlueFey, Long> {

    public static final String TABLENAME = "BLUE_FEY";

    /**
     * Properties of entity BlueFey.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BlueUrl = new Property(1, String.class, "blueUrl", false, "BLUE_URL");
        public final static Property BlueName = new Property(2, String.class, "blueName", false, "BLUE_NAME");
    };


    public BlueFeyDao(DaoConfig config) {
        super(config);
    }
    
    public BlueFeyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BLUE_FEY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"BLUE_URL\" TEXT," + // 1: blueUrl
                "\"BLUE_NAME\" TEXT);"); // 2: blueName
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BLUE_FEY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BlueFey entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String blueUrl = entity.getBlueUrl();
        if (blueUrl != null) {
            stmt.bindString(2, blueUrl);
        }
 
        String blueName = entity.getBlueName();
        if (blueName != null) {
            stmt.bindString(3, blueName);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BlueFey readEntity(Cursor cursor, int offset) {
        BlueFey entity = new BlueFey( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // blueUrl
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // blueName
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BlueFey entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBlueUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBlueName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BlueFey entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BlueFey entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
