package com.myblue.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.myblue.dao.BlueFey;

import com.myblue.dao.BlueFeyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig blueFeyDaoConfig;

    private final BlueFeyDao blueFeyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        blueFeyDaoConfig = daoConfigMap.get(BlueFeyDao.class).clone();
        blueFeyDaoConfig.initIdentityScope(type);

        blueFeyDao = new BlueFeyDao(blueFeyDaoConfig, this);

        registerDao(BlueFey.class, blueFeyDao);
    }
    
    public void clear() {
        blueFeyDaoConfig.getIdentityScope().clear();
    }

    public BlueFeyDao getBlueFeyDao() {
        return blueFeyDao;
    }

}
